export const COMMON_EXERCISES = [
  'Bench Press',
  'Assisted Dumbells Press',
  'Butterfly',
  'Reverse Butterfly',
  'Shoulder Press',
  'Biceps Curls Machine',
  'Bicep Curls',
  'Seated Biceps Curls',
  'Lateral Raise Rope',
  'Lat Pulldowns',
  'Leg Press',
  'Leg Extension',
  'Seated Leg Curl',
  'Unilateral Triceps Rope',
  'Triceps Rope',
  'Triceps Rope Bar',
  'Lat Bar Rope',
];
